language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t valerivk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true valerivk/react-test npm test

after_success:
  - docker build -t valerivk/multi-client ./client
  - docker build -t valerivk/multi-nginx ./nginx
  - docker build -t valerivk/multi-server ./server
  - docker build -t valerivk/multi-worker ./worker
